import './globals.css';
import { Inter, IBM_Plex_Sans } from 'next/font/google';
import { ThemeProvider } from '~/components/theme-provider';
import { Analytics } from '~/components/analytics';
import TopNavBar from '~/components/TopNav';

const inter = IBM_Plex_Sans({
	weight: ['100', '200', '300', '400', '500', '600', '700'],
	subsets: ['latin']
});

export const metadata = {
	title: "Sharukh's Blog",
	description: 'Generated by create next app'
};

interface RootLayoutProps {
	children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className} antialiased min-h-screen bg-[url('bg-white.svg')] dark:bg-[url('bg-black.svg')] bg-center bg-repeat bg-auto `}>
				<ThemeProvider attribute='class' defaultTheme='dark' enableSystem>
					<div className='flex flex-col'>
						<TopNavBar />
						<main>{children}</main>
					</div>
					<Analytics />
				</ThemeProvider>
			</body>
		</html>
	);
}
// <div className='grid grid-cols-10'>
// <div className='col-span-2 bg-gray-200'>20% width column</div>
// <div className='col-span-6 bg-gray-300'>60% width column</div>
// <div className='col-span-2 bg-gray-400'>20% width column</div>
// </div>;
